"""Render (and drift-check) the ecosystem compatibility manifest.

``ecosystem/compatibility.toml`` is the single source of truth for the
supported combination. This script derives every consumable view from it:

- ``requirements/verified.txt``  — pip-installable pinned combination
  (a requirements file, NOT a constraints file: pip constraints cannot
  contain direct references, and everything except lazybridge is a
  ``pkg @ git+...`` direct reference);
- ``ecosystem/compatibility.json`` — machine-readable view for CI;
- ``ecosystem/compatibility.md``   — Markdown table for the website.

Usage:
    python tools/render_compatibility.py            # (re)write the views
    python tools/render_compatibility.py --check    # fail on any drift

``--check`` fails when:
- a generated view on disk does not match what the TOML produces;
- a ``git+https://github.com/selvaz/<Repo>.git@<ref>`` reference anywhere
  in this repo (pyproject.toml, workflows, README) uses a ref different
  from the manifest's for that repository;
- this package's lazybridge requirement does not admit the verified
  lazybridge version.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys
import tomllib

from packaging.requirements import Requirement
from packaging.version import Version

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "ecosystem" / "compatibility.toml"

REQUIREMENTS_OUT = REPO_ROOT / "requirements" / "verified.txt"
JSON_OUT = REPO_ROOT / "ecosystem" / "compatibility.json"
MD_OUT = REPO_ROOT / "ecosystem" / "compatibility.md"

# Files scanned for Git direct references that must agree with the manifest.
SCAN_GLOBS = ["pyproject.toml", ".github/workflows/*.yml", "README.md"]

GIT_REF_RE = re.compile(r"git\+https://github\.com/selvaz/([A-Za-z0-9_.-]+?)(?:\.git)?@([A-Za-z0-9_.\-/]+)")


def load_manifest() -> dict:
    return tomllib.loads(MANIFEST.read_text(encoding="utf-8"))


def render_requirements(m: dict) -> str:
    lines = [
        "# GENERATED by tools/render_compatibility.py from ecosystem/compatibility.toml",
        "# — do not edit by hand. The verified, co-installable combination:",
        "#   pip install -r requirements/verified.txt",
        "",
        f"lazybridge=={m['verified']['lazybridge']}",
    ]
    for name, entry in m["verified"]["github"].items():
        extras = f"[{','.join(entry['extras'])}]" if entry.get("extras") else ""
        lines.append(f"{name}{extras} @ git+{entry['repo']}.git@{entry['ref']}")
    for name, entry in m.get("pending", {}).items():
        lines.append(f"# EXCLUDED {name}: {entry['reason']}")
    return "\n".join(lines) + "\n"


def render_json(m: dict) -> str:
    return json.dumps(m, indent=2, sort_keys=True) + "\n"


def render_markdown(m: dict) -> str:
    rows = [
        "<!-- GENERATED by tools/render_compatibility.py — do not edit by hand -->",
        "",
        "# Verified ecosystem combination",
        "",
        f"Python: {', '.join(m['verified']['python'])}",
        "",
        "| Component | Channel | Verified ref |",
        "|---|---|---|",
        f"| lazybridge | PyPI | `{m['verified']['lazybridge']}` |",
    ]
    for name, entry in m["verified"]["github"].items():
        rows.append(f"| {name} | GitHub | `{entry['ref']}` |")
    for name, entry in m.get("pending", {}).items():
        rows.append(f"| {name} | GitHub | *excluded* — {entry['reason']} |")
    return "\n".join(rows) + "\n"


def scan_repo_refs(m: dict) -> list[str]:
    """Every selvaz Git direct reference in the repo must match the manifest."""
    by_repo: dict[str, str] = {}
    for entry in m["verified"]["github"].values():
        by_repo[entry["repo"].rsplit("/", 1)[-1].lower()] = entry["ref"]

    errors = []
    for glob in SCAN_GLOBS:
        for path in REPO_ROOT.glob(glob):
            text = path.read_text(encoding="utf-8", errors="replace")
            for repo, ref in GIT_REF_RE.findall(text):
                want = by_repo.get(repo.lower())
                if want is None:
                    errors.append(f"{path.relative_to(REPO_ROOT)}: reference to {repo!r} which is not in the manifest")
                elif ref != want:
                    errors.append(
                        f"{path.relative_to(REPO_ROOT)}: {repo} pinned to {ref!r}, manifest says {want!r}"
                    )
    return errors


def check_lazybridge_range(m: dict) -> list[str]:
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    verified = Version(m["verified"]["lazybridge"])
    for dep in pyproject["project"]["dependencies"]:
        req = Requirement(dep)
        if req.name == "lazybridge" and verified not in req.specifier:
            return [f"pyproject lazybridge range {req.specifier} does not admit verified {verified}"]
    return []


def main() -> int:
    m = load_manifest()
    views = {
        REQUIREMENTS_OUT: render_requirements(m),
        JSON_OUT: render_json(m),
        MD_OUT: render_markdown(m),
    }

    if "--check" in sys.argv:
        errors: list[str] = []
        for path, want in views.items():
            rel = path.relative_to(REPO_ROOT)
            if not path.exists():
                errors.append(f"{rel}: missing — run tools/render_compatibility.py")
            elif path.read_text(encoding="utf-8").replace("\r\n", "\n") != want:
                errors.append(f"{rel}: stale — run tools/render_compatibility.py")
        errors += scan_repo_refs(m)
        errors += check_lazybridge_range(m)
        if errors:
            print("compatibility manifest drift detected:")
            for e in errors:
                print(f"  - {e}")
            return 1
        print("compatibility manifest: no drift")
        return 0

    for path, content in views.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
